### ISSUE TITLE
D5200 patch locations

### ISSUE THREAD

**Issue by ian5142** [simeonpilgrim/nikon-firmware-tools#88]
Hello,
Are the patch locations between the different firmware versions the same? For example, the patch does not currently support v1.03, can I use the locations from v1.02 and modify your code to make it work with v1.03?

I really want the No-liveview timeout and 40/64MB HQ video. I would also like to eventually port over the following patches from D5100:   remove time-based video restrictions, Jpeg Quality and disable Nikon star eater. These are just hopefuls. 

See my previous issue here: https://github.com/simeonpilgrim/nikon-firmware-tools/issues/79

I have vast amounts of spare time and can test any firmware. I have experience recovering various devices using serial, JTAG, etc. I don't mind setting up a build environment for the project but I don't know where to start modifying the scripts to handle v1.03.

**Comment by simeonpilgrim** [comment]
the locations "are the same" insofar as does the linker place all objects in the same location each time.. which is a no.. but that are close enough..

The loading one firmware version in IDA Pro or Ghidra and then loading the next version, and finding the "same" surrounding code, and use patterns makes porting across firmware versions not too hard, for simple jump patches.

Moving stuff between camera's like the D5100 (FR based) to D5200 (Arm based) is a start from scratch thing, albeit the concept of the change can apply, because they are doing the same thing (tm)

**Comment by ian5142** [comment]
OK, what do you consider the "same surrounding code. I am currently examining the differences between v1.03 and v1.02 in HxD.

**Comment by fenugrec** [comment]
speaking from experience on entirely different firmware RE, "same surrounding code" involves recognizing a function, or a data structure, (as closely related to the parameter you're looking for as possible), common to both firmware versions, with a very high confidence.
Usually matching functions will have very similar call graphs, flow charts; will call (or be called) by other functions that are recognizable or identical between both firmwares.
